compliance-container:
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-compliance:89
  links:
  - jupiter-container:jupiter
  - rabbitmq-container:rabbitmq
  volumes:
  - logs:/datayes/trading/logs
  stdin_open: true
redis-container:
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: 10.0.0.10:5002/admin/trading-redis:89
  stdin_open: true
ems-container:
  ports:
  - 11001:11001/tcp
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: hostname=${host}
  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-ems:89
  links:
  - redis-container:redis
  volumes:
  - logs:/datayes/trading/workspace/logs
  stdin_open: true
proxyserver-container:
  ports:
  - 3337:3336/tcp
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}

  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: hostname=${host}

  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-proxyserver:89
  links:
  - jupiter-container:jupiter
  - rabbitmq-container:rabbitmq
  volumes:
  - logs:/datayes/trading/logs
  stdin_open: true
simulator-container:
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}

  labels:
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-simulator:89
  links:
  - mysql-container:mysql
  volumes:
  - logs:/datayes/trading/logs
  stdin_open: true
brokergateway-container:
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}

  labels:
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-brokergateway:89
  links:
  - mysql-container:mysql
  - ems-container:ems
  - fixgateway-container:fixgateway
  - rabbitmq-container:rabbitmq
  volumes:
  - logs:/datayes/trading/logs
  stdin_open: true
mysql-container:
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}

  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: 10.0.0.10:5002/admin/trading-mysql:89 
  stdin_open: true
jupiter-container:
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-jupiter:89
  links:
  - mysql-container:mysql
  - rabbitmq-container:rabbitmq
  volumes:
  - logs:/datayes/trading/logs
  stdin_open: true
rabbitmq-container:
  ports:
  - 15672:15672/tcp
  - 5674:5672/tcp
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}

  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: hostname=${host}
  tty: true
  image: 10.0.0.10:5002/admin/trading-rabbitmq:89
  stdin_open: true
webapi-container:
  ports:
  - 8091:8080/tcp
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: hostname=${host}
  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-webapi:89
  links:
  - proxyserver-container:proxyserver
  volumes:
  - logs:/datayes/trading/logs
  stdin_open: true
fixgateway-container:
  environment:
    TZ: Asia/Shanghai
    MDL_IP: ${mdl_ip}
    MDL_PORT: ${mdl_port}
  domainname: 10.21.235.30
  labels:
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 10.21.235.30
  image: 10.0.0.10:5002/admin/trading-fixgateway:89
  links:
  - mysql-container:mysql
  volumes:
  - logs:/datayes/trading/logs
  stdin_open: true
